version: "3"

services:
  bot:
    build: ./bot/
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./configs:/workspace/bot/configs/
      - ./irc_logs:/workspace/bot/irc_logs/
      - ./jsons:/workspace/bot/jsons/
      # - ./bot:/workspace/bot/

  webserver:
    build: ./web/
    restart: unless-stopped
    expose:
      - 5000
    depends_on:
      - mysql

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`${WEB_HOSTNAME}`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"

    # Uncommenting these disables the requirement to re-build on updates, useful for dev.
    # volumes:
    #   - ./web:/workspace/web/

  mysql:
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: twitchbot
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "./traefik/acme.json:/acme.json"
    environment:
      - "TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL"
